# Generated by Django 5.1.2 on 2024-10-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client'), ('Manager', 'Manager'), ('Cleaner', 'Cleaner')], max_length=30),
        ),
    ]
