# Generated by Django 5.0.4 on 2024-10-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client'), ('Supervisor', 'Supervisor'), ('Cleaner', 'Cleaner')], max_length=30),
        ),
    ]
