# Generated by Django 5.0.4 on 2024-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
