# Generated by Django 5.0.4 on 2024-09-19 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanuprequest',
            old_name='deleteStatus',
            new_name='delete_status',
        ),
        migrations.RenameField(
            model_name='cleanuprequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deleteStatus',
            new_name='delete_status',
        ),
        migrations.RemoveField(
            model_name='cleanuprequest',
            name='assigned_manager',
        ),
        migrations.RemoveField(
            model_name='cleanuprequest',
            name='is_approved_by_admin',
        ),
        migrations.RemoveField(
            model_name='cleanuprequest',
            name='is_approved_by_manager',
        ),
        migrations.RemoveField(
            model_name='cleanuprequest',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='cleanuprequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cleanuprequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanuprequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cleanup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleanuprequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanuprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='cleaners',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanuprequest',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cleanuprequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cleanuprequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
