# Generated by Django 5.0.4 on 2024-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_manager_cleanuprequest_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanuprequest',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
