# Generated by Django 5.1.2 on 2024-10-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_task_description_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanuprequest',
            old_name='company',
            new_name='manager',
        ),
    ]
