# Generated by Django 5.0.4 on 2024-10-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cleanuprequest_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanuprequest',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
