# Generated by Django 5.0.4 on 2024-11-04 10:33

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, help_text='Upload only PDF files', null=True, upload_to=home.models.invoice_file_path),
        ),
    ]
