# Generated by Django 5.0.4 on 2024-11-19 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_invoice_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'Supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='weeklyreports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Weekly Reports',
            },
        ),
    ]
