# Generated by Django 5.0.4 on 2024-11-19 18:09

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_weeklyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='file',
            field=models.FileField(blank=True, help_text='Upload only PDF files', null=True, upload_to=home.models.report_file_path),
        ),
    ]
